### ISSUE TITLE
Bitgo blake2b repository missing

### ISSUE THREAD

**Issue by abcdevs** [Crypto-APIs/Crypto_APIs_Key_Management_System#2]
It appears the repository has been completely removed from github and the install fails to complete.

This is the install error:
`npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/BitGo/blake2b.git`

Both bitgo/blake2b and bitgo/blake2b-wasm repositories are missing.

**Comment by malin-globalinfratech** [comment]
Hi @abcdevs ,
It seems like some dependency repositories changed their names. It should all be fine now in version `v0.7.1`
Hope it helps,
Cheers

**Comment by abcdevs** [comment]
Worked like a charm, thanks!
